name: C++ Hardcore CI

on:
  push:
    branches: ['**'] 
  pull_request:
    branches: ['**']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++-13, clang++-18] 

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            libssl-dev \
            clang-18

      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror -fsanitize=address,undefined"

      - name: Build
        run: cmake --build build --parallel $(nproc)

      - name: Run Tests (CTest)
        working-directory: build
        run: |

          sudo prlimit --pid=$$ --memlock=unlimited:unlimited
          ctest --output-on-failure --verbose